### ISSUE TITLE
[feature]どこかのタイミングでGitHub Organization化する

### ISSUE THREAD

**Issue by haruu11113** [cam-grad/Code4YoungInnovator#23]
## [概要]
記事に関連したリポジトリをまとめて管理できるよう、Orgnizaion化する。

## [課題]
議論すべき点
- [ ] いつやるのか？
- [ ] リポジトリの運用ルール策定
- [ ] 運用ルールの公開方法決定
- [ ] ライセンス定める？各リポジトリで決定？

## [解決すること]
- 記事 + コードが必ずあるという信頼性を担保
- コピーすれば必ず動く
- 記事には書かないコードも見れ、コードの全体間がイメージしやすい

## [技術案・メモ]
- notion databaseにgithubのURLをカラムでつける？

**Comment by haruu11113** [comment]
> いつやるのか？

について、正式リリース時？で良い気がする。
- (要調査) issueなどが引き継げるのかが懸念点

**Comment by sakaaya** [comment]
https://github.com/cam-grad/test/issues
これで手元のテストリポジトリを作ってIssueが引き継がれるかみてみたらちゃんと引き継がれてた🎉
